name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn package
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts
