name: test
on:
  push:
    branches: [main]
  pull_request:
  pull_request_target:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --immutable
      - run: yarn test --ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --immutable
      - run: yarn lint
